/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Bushido Blade 2)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800836ECu
#define func_800836EC BootEntry  /* alias */
